name: mh_clean_framework_sample
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clean_framework: ^2.0.4
  clean_framework_router: ^0.4.0
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  flutter_rating_stars: ^1.0.3+4
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  clean_framework_test: ^0.4.1
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  riverpod: ^2.1.3
  meta: ^1.8.0
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.2

import_sorter:
  comments: false

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
